export const skills: Array<String> = [
  "Typescript/Javascript",
  "Python",
  "Golang",
  "PHP",
  "Nestjs",
  "Django",
  "Laravel",
  "Express",
  "Linux",
  "MySQL/MariaDB",
  "PostgreSQL",
  "MongoDB",
  "Docker",
  "React/Nextjs",
  "Vue",
  "Tailwind CSS",
  "Redis",
  "Git/Github",
];
